Repository rancher/elemental, pull requests merged in 2022-12, with the labels that each got.

#549 Delete OS version and channel in e2e UI tests
  cypress/e2e/unit_tests/machine_registration.spec.ts
  cypress/e2e/unit_tests/upgrade.spec.ts
  cypress/support/e2e.ts
  cypress/support/functions.ts
Labels: kind/QA

#556 ci/e2e: fix path for artifacts
  .github/workflows/master-e2e.yaml
Labels: kind/QA

#559 Convert runner_template to input variable
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e-k3s.yaml
  .github/workflows/ui-e2e-rke2.yaml
Labels: kind/QA

#561 Update README CI badges
  README.md
Labels: kind/QA

#562 ci/e2e: add elemental-operator version in summary
  .github/workflows/master-e2e.yaml
Labels: area/elemental, kind/QA

#563 ci/ui: fix empty variables in scheduled test
  .github/workflows/ui-e2e-k3s.yaml
Labels: kind/QA, area/UI

#564 ci/ui: fix empty variables in scheduled test - part 2
  .github/workflows/ui-e2e-rke2.yaml
Labels: kind/QA, area/UI

#569 Remove syncInterval if operator vers is 1.0 (UI)
  .github/workflows/master-e2e.yaml
  cypress/e2e/unit_tests/upgrade.spec.ts
  cypress/plugins/index.ts
  tests/scripts/start_cypress_tests.sh
Labels: kind/QA

#570 Remove two CI steps not needed anymore due to ephemeral GH runners
  .github/workflows/master-e2e.yaml
Labels: kind/QA

#574 Collect elemental support in e2e UI CI
  .github/workflows/master-e2e.yaml
  tests/Makefile
  tests/e2e/logs_test.go
  tests/e2e/suite_test.go
Labels: kind/QA

#572 Increase timeout to delete a resource with Cypress
  cypress/support/functions.ts
Labels: kind/QA

#581 Disable Rancher extension repository in UI tests
  cypress/e2e/unit_tests/elemental_plugin.spec.ts
Labels: kind/QA

#589 Deploy sample app through UI in Elemental cluster
  .github/workflows/master-e2e.yaml
  cypress/e2e/unit_tests/deploy_app.spec.ts
Labels: kind/QA

#595 Fix path for Cypress artifacts upload
  .github/workflows/master-e2e.yaml
Labels: kind/QA

#598 ci: fix generated README for tests description
  .github/workflows/master-e2e.yaml
  .github/workflows/update-tests-description.yaml
Labels: kind/QA

#599 ci: use the same PAT token for CI
  .github/workflows/update-tests-description.yaml
Labels: kind/QA

#594 Add proxy tests in UI
  .github/workflows/e2e-k3s-obs-Dev.yaml
  .github/workflows/e2e-k3s-obs-Stable.yaml
  .github/workflows/e2e-k3s-obs-Staging.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e-k3s.yaml
  tests/assets/squid.conf
  tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/plugins/index.ts
  tests/e2e/install_test.go
  tests/e2e/suite_test.go
  tests/scripts/start-cypress-tests
Labels: kind/QA

#600 Configure proxy in UI tests only
  .github/workflows/e2e-k3s-obs-Dev.yaml
  .github/workflows/e2e-k3s-obs-Stable.yaml
  .github/workflows/e2e-k3s-obs-Staging.yaml
  .github/workflows/ui-e2e-k3s-obs-Dev.yaml
  .github/workflows/ui-e2e-k3s-obs-Stable.yaml
  .github/workflows/ui-e2e-k3s-obs-Staging.yaml
Labels: kind/QA
