Repository rancher/elemental, pull requests merged in 2022-09, with the labels that each got.

#308 docs: Add smbios docs
  docs/machineregistration-reference.md
  docs/smbios.md
  examples/quickstart/registration.yaml
  mkdocs.yml
Labels: blocked, area/docs

#296 Bootstrap a node to join UI (Cypress)
  .github/workflows/ui-e2e.yaml
  cypress.json
  cypress/integration/unit_tests/machine_inventory.spec.ts
  cypress/integration/unit_tests/machine_registration.spec.ts
  cypress/plugins/index.ts
  scripts/start_cypress_tests.sh
  tests/Makefile
  tests/e2e/ui_test.go
Labels: QA, UI

#315 ci/e2e: add TPM emulation test
  .github/workflows/e2e.yaml
  tests/assets/emulated_tpm.yaml
  tests/e2e/bootstrap_test.go
  tests/e2e/configure_test.go
  tests/e2e/suite_test.go
  tests/scripts/install-vm
Labels: area/elemental, QA

#320 Add elemental-support binary in generated image
  Dockerfile.image
Labels: area/elemental, QA

#299 ci: re-add integration tests
  .github/workflows/build-ci.yaml
  .github/workflows/integration.yaml
  Makefile
  tests/Makefile
  tests/Vagrantfile
  tests/assets/cloud_init.yaml
  tests/assets/external_charts.yaml
  tests/assets/rancherd.yaml
  tests/assets/setting.yaml
  tests/install/install_suite_test.go
  tests/install/install_test.go
  tests/smoke/smoke_suite_test.go
  tests/smoke/smoke_test.go
  tests/sut/sut.go
  tests/tests_suite_test.go
Labels: area/elemental, QA

#328 Add machine selector Cypress tests
  .github/workflows/ui-e2e.yaml
  cypress.json
  cypress/integration/unit_tests/machine_selector.spec.ts
  cypress/support/elemental.ts
  tests/assets/machineregistration.yaml
Labels: QA, UI

#330 docs: drop config:elemental:registration:labels field
  docs/machineregistration-reference.md
Labels: documentation, area/docs

#329 ci/e2e: re-add upgrade with managedOSVersionName
  .github/workflows/e2e.yaml
  examples/upgrade/upgrade-node-selector.yaml
  tests/assets/managedOSVersionChannel.yaml
  tests/assets/osVersions.json
  tests/e2e/bootstrap_test.go
  tests/e2e/configure_test.go
  tests/e2e/helpers/misc/misc.go
  tests/e2e/suite_test.go
  tests/e2e/upgrade_test.go
Labels: area/elemental, QA

#344 Add a basic upgrade test triggered from the UI
  .github/workflows/ui-e2e.yaml
  cypress.json
  cypress/integration/unit_tests/upgrade.spec.ts
Labels: QA, UI

#345 ci/e2e: add K3s cluster provisioning test
  .github/workflows/e2e.yaml
  .github/workflows/master-e2e.yaml
  tests/e2e/bootstrap_test.go
Labels: area/elemental, QA

#359 Use EFI firmware for CI
  Makefile
  tests/Makefile
  tests/install/install_test.go
Labels: area/elemental, area/QA

#360 Add Cypress tests to check OS versions channels
  cypress/integration/unit_tests/upgrade.spec.ts
  package.json
Labels: area/QA, UI

#367 ci/e2e: use new self-hosted runner
  .github/workflows/e2e.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e.yaml
Labels: area/elemental, area/QA

#370 ci/e2e: secret shouldn't be directly configured in master
  .github/workflows/e2e.yaml
  .github/workflows/master-e2e.yaml
Labels: area/elemental, area/QA

#371 ci/e2e: fix wrong K3s version
  .github/workflows/master-e2e.yaml
Labels: area/elemental, area/QA
