Repository rancher/elemental, pull requests merged in 2022-11, with the labels that each got.

#506 ci/ui: remove number of installed nodes from summary
  .github/workflows/master-e2e.yaml
Labels: area/elemental, area/QA

#513 Add UI test to check default cloud-config
  cypress/e2e/unit_tests/machine_registration.spec.ts
  cypress/support/e2e.ts
  cypress/support/functions.ts
Labels: kind/QA

#519 docs: small improvment in backup
  docs/backup.md
Labels: area/elemental, area/docs

#527 ci/e2e: make Rancher version configurable
  .github/workflows/e2e-obs-Dev.yaml
  .github/workflows/e2e-obs-Stable.yaml
  .github/workflows/e2e-obs-Staging.yaml
Labels: area/elemental, kind/QA

#536 Test advanced filtering in Elemental UI
  .github/workflows/master-e2e.yaml
  cypress/e2e/unit_tests/advanced_filtering.spec.ts
  cypress/fixtures/machine_inventory_1.yaml
  cypress/fixtures/machine_inventory_2.yaml
  cypress/fixtures/machine_inventory_3.yaml
  cypress/support/e2e.ts
  cypress/support/functions.ts
Labels: kind/QA

#537 Remove fake machine inventories (Cypress tests)
  cypress/e2e/unit_tests/advanced_filtering.spec.ts
Labels: kind/QA

#544 ci/e2e: use new elemental-operator helm chart
  .github/workflows/e2e-obs-Dev.yaml
  .github/workflows/e2e-obs-Stable.yaml
  .github/workflows/e2e-obs-Staging.yaml
Labels: kind/QA, area/elemental-operator

#543 Restart fleet to avoid sporadic failures in UI tests
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e.yaml
  cypress/e2e/unit_tests/upgrade.spec.ts
  tests/e2e/install_test.go
  tests/e2e/suite_test.go
Labels: kind/QA
