Repository rancher/elemental, pull requests merged in 2022-08, with the labels that each got.

#201 Re add e2e tests
  .github/workflows/build-ci.yaml
  .github/workflows/e2e.yaml
  Makefile
  tests/assets/add_cluster.yaml
  tests/assets/cluster.yaml
  tests/assets/machineregistration.yaml
  tests/assets/net-default.xml
  tests/assets/selector.yaml
  tests/e2e/README.md
  tests/e2e/bootstrap_test.go
  tests/e2e/helpers/misc/misc.go
  tests/e2e/install_test.go
  tests/e2e/suite_test.go
  tests/go.mod
  tests/go.sum
  tests/install/install_test.go
  tests/smoke/smoke_test.go
Labels: QA

#238 E2E: add SetTimeout function for slow runner
  .github/workflows/e2e.yaml
  tests/e2e/README.md
  tests/e2e/bootstrap_test.go
  tests/e2e/helpers/misc/misc.go
  tests/e2e/install_test.go
  tests/e2e/suite_test.go
  tests/e2e/upgrade_test.go
Labels: area/elemental, QA, area/teal

#253 Small improvements to the info generated via the build iso script
  elemental-iso-build
Labels: enhancement, area/elemental, area/teal

#252 Add quickstart
  docs/quickstart.md
  examples/quickstart/cluster.yaml
  examples/quickstart/registration.yaml
  examples/quickstart/selector.yaml
  mkdocs.yml
Labels: documentation, area/elemental, area/teal

#262 Expand quickstart docs
  docs/quickstart.md
Labels: documentation

#264 Add plans doc
  docs/elemental-plans.md
  mkdocs.yml
Labels: documentation, area/elemental

#268 Improve docs
  docs/architecture.md
  docs/dashboard.md
  docs/installation.md
  docs/kubernetesversions.md
  docs/mcm.md
  docs/quickstart.md
  docs/upgrade.md
  docs/versions.md
  examples/upgrade/managed-os-version-channel-json.yaml
  examples/upgrade/versions.json
  mkdocs.yml
Labels: area/elemental, area/docs

#271 Add reference docs
  docs/cloud-config-reference.md
  docs/configuration.md
  docs/machineregistration-reference.md
  mkdocs.yml
Labels: area/elemental, area/docs

#270 Add some basic checks to iso generated by elemental-iso-build
  .github/workflows/build-iso.yaml
  elemental-iso-build
Labels: area/elemental, automation

#229 Add leftover test cases for machine reg in UI
  cypress/integration/unit_tests/machine_registration.spec.ts
  cypress/support/functions.ts
  cypress/support/index.ts
Labels: QA

#278 e2e: don't use a container anymore
  .github/workflows/e2e.yaml
  tests/e2e/bootstrap_test.go
  tests/e2e/install_test.go
  tests/scripts/install-vm
Labels: area/elemental, QA

#277 Add Cypress tests in the CI
  .github/workflows/ui-e2e.yaml
  Makefile
  scripts/install_rancher.sh
  scripts/start_cypress_tests.sh
Labels: QA

#286 Test Machine reg YAML edition with Cypress
  cypress/integration/unit_tests/machine_registration.spec.ts
  cypress/support/functions.ts
  cypress/support/index.ts
Labels: QA

#287 Convert bash code to golang
  .github/workflows/e2e.yaml
  .github/workflows/ui-e2e.yaml
  Makefile
  scripts/install_rancher.sh
  tests/Makefile
  tests/e2e/configure_test.go
  tests/e2e/install_test.go
Labels: QA

#289 Readd e2e upgrade tests
  .github/workflows/e2e.yaml
  tests/assets/upgrade_clusterTargets.yaml
  tests/e2e/README.md
  tests/e2e/upgrade_test.go
Labels: automation, QA

#293 Add status badge for e2e tests
  README.md
Labels: QA
