Repository rancher/elemental, pull requests merged in 2022-10, with the labels that each got.

#380 ci/e2e: update test plan
  tests/e2e/README.md
  tests/e2e/install_test.go
Labels: area/elemental, area/QA

#378 ci/e2e: use EFI firmware instead of deprecated BIOS
  .github/workflows/master-e2e.yaml
  tests/assets/net-default.xml
  tests/scripts/install-vm
Labels: area/elemental, area/QA

#387 ci/e2e+ui: set condition to start the runner
  .github/workflows/e2e.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e.yaml
Labels: area/elemental, area/QA, UI

#388 ci/e2e+ui: set condition to start the runner #2
  .github/workflows/e2e.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e.yaml
Labels: area/elemental, area/QA, UI

#389 ci/e2e+ui: set condition to start the runner #2
  .github/workflows/e2e.yaml
Labels: area/elemental, area/QA, UI

#390 ci/e2e+ui: fix Cypress upload + timeout
  .github/workflows/master-e2e.yaml
  tests/e2e/bootstrap_test.go
Labels: area/elemental, area/QA, UI

#392 ci/ui: use a different group than the CLI E2E tests
  .github/workflows/ui-e2e.yaml
Labels: area/elemental, area/QA, UI

#393 Fix e2e tests group
  .github/workflows/e2e.yaml
  .github/workflows/ui-e2e.yaml
Labels: area/elemental, area/QA, UI

#394 ci/e2e: test custom machineName
  tests/assets/machineregistration.yaml
Labels: area/elemental, area/QA

#395 ci/e2e: increase test to 5 nodes
  .github/workflows/master-e2e.yaml
  tests/assets/net-default.xml
Labels: area/elemental, area/QA

#401 Use a dedicated runner for UI test (spot VM)
  .github/workflows/ui-e2e.yaml
Labels: area/automation, area/QA

#404 Use GCP spot instance for the backend e2e CI
  .github/workflows/e2e.yaml
Labels: area/automation, area/QA

#406 Migrate to Cypress 10.9
  .github/workflows/master-e2e.yaml
  cypress.config.ts
  cypress.json
  cypress/e2e/unit_tests/first_connection.spec.ts
  cypress/e2e/unit_tests/machine_inventory.spec.ts
  cypress/e2e/unit_tests/machine_registration.spec.ts
  cypress/e2e/unit_tests/machine_selector.spec.ts
  cypress/e2e/unit_tests/menu.spec.ts
  cypress/e2e/unit_tests/upgrade.spec.ts
  cypress/support/e2e.ts
  package.json
  scripts/start_cypress_tests.sh
Labels: area/automation, area/QA

#415 docs: rework the Architecture section
  docs/architecture.md
  mkdocs.yml
Labels: draft

#427 ci/e2e: fix issue with stable/latest
  .github/workflows/e2e.yaml
Labels: area/elemental, area/QA

#438 ci/e2e: force HTTP1.1 for curl download
  .github/workflows/master-e2e.yaml
Labels: area/elemental, area/QA

#439 Use a dedicated group for UI tests
  .github/workflows/ui-e2e.yaml
Labels: area/QA

#450 ci/e2e: add retry on curl command
  .github/workflows/master-e2e.yaml
Labels: area/elemental, area/QA

#459 ci/e2e: better to use wget instead curl
  .github/workflows/master-e2e.yaml
Labels: area/elemental, area/QA

#460 Network: Make NM ignore calico and flannel devices
  framework/files/etc/NetworkManager/conf.d/rke2-canal.conf
Labels: area/elemental, area/network

#461 docs: small changes to reference section
  docs/elementaloperatorchart-reference.md
  docs/machineinventoryselectortemplate-reference.md
  docs/machineregistration-reference.md
Labels: kind/documentation

#462 docs: update clusters+quickstart
  docs/cluster-reference.md
  docs/quickstart.md
  examples/clusters/clusters-several-machinepools.yml
  mkdocs.yml
Labels: area/docs

#469 ci/integration: refactoring + cleaning
  .github/workflows/integration.yaml
  .gitignore
  tests/Makefile
  tests/install/install_test.go
  tests/prepare_cloudinit
Labels: area/elemental, area/QA

#468 Use the elemental plugin in the UI CI
  .github/workflows/e2e-obs-Dev.yaml
  .github/workflows/e2e-obs-Stable.yaml
  .github/workflows/e2e-obs-Staging.yaml
  .github/workflows/e2e.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e.yaml
  cypress/e2e/unit_tests/elemental_plugin.spec.ts
  cypress/support/e2e.ts
  cypress/support/elemental.ts
  cypress/support/functions.ts
  package.json
  tests/e2e/install_test.go
Labels: area/QA

#272 Docs migration to Docusaurus
  .gitignore
  Vars.js
  babel.config.js
  docs/architecture.md
  docs/backup.md
  docs/cloud-config-reference.md
  docs/cluster-reference.md
  docs/customizing.md
  docs/elemental-plans.md
  docs/elementaloperatorchart-reference.md
  docs/index.md
  docs/installation.md
  docs/inventory-management.md
  docs/kubernetesversions.md
  docs/machineinventoryselectortemplate-reference.md
  docs/machineregistration-reference.md
  docs/quickstart.md
  docs/restore.md
  docs/smbios.md
  docs/tpm.md
  docs/upgrade.md
  docusaurus.config.js
  examples/elemental.cattle.io/v1beta1/MachineRegistration.yaml
  package.json
  sidebars.js
  src/components/HomepageFeatures/styles.module.css
  src/css/custom.css
  src/pages/index.module.css
  src/theme/MDXComponents/A.js
  src/theme/MDXComponents/Code.js
  src/theme/MDXComponents/Details.js
  src/theme/MDXComponents/Head.js
  src/theme/MDXComponents/Heading.js
  src/theme/MDXComponents/Pre.js
  src/theme/MDXComponents/index.js
  static/.nojekyll
  static/img/docusaurus.png
  static/img/favicon.ico
  static/img/logo.svg
  static/img/undraw_docusaurus_mountain.svg
  static/img/undraw_docusaurus_react.svg
  static/img/undraw_docusaurus_tree.svg
  tsconfig.json
  yarn.lock
Labels: area/docs
