Repository rancher/elemental, pull requests merged in 2022-07, with the labels that each got.

#191 ci: better to use actions-setup-docker to install docker
  .github/workflows/build-iso.yaml
Labels: QA

#190 Use new elemental-cli repo
  Makefile
Labels: blocked

#200 Add Cypress tests into the repo
  .gitignore
  cypress.json
  cypress/integration/unit_tests/first_connection.spec.ts
  cypress/integration/unit_tests/menu.spec.ts
  cypress/plugins/index.ts
  cypress/support/elemental.ts
  cypress/support/functions.ts
  cypress/support/index.ts
  cypress/support/toplevelmenu.ts
  package.json
  tsconfig.json
Labels: QA

#214 build: remove obsolete elemental.install.* options
  iso/grub.cfg
Labels: bug, area/elemental

#209 Add Cypress tests for Machine Registration
  cypress.json
  cypress/integration/unit_tests/machine_registration.spec.ts
  cypress/plugins/index.ts
  cypress/support/functions.ts
  cypress/support/index.ts
  package.json
  tsconfig.json
Labels: QA

#226 Update bootargs.cfg
  framework/files/etc/cos/bootargs.cfg
Labels: area/elemental, area/teal
