Repository rancher/elemental, pull requests merged in 2023-02, with the labels that each got.

#644 ci/e2e: increase timeout when delete resource in UI
  tests/cypress/support/functions.ts
Labels: kind/QA

#646 ci/e2e: fix E2E scheduled tests with latest RMS
  .github/workflows/e2e-k3s-latest.yaml
  .github/workflows/e2e-rke2-latest.yaml
Labels: area/elemental, kind/QA

#658 ci/e2e: increase default node number to 10
  .github/workflows/master-e2e.yaml
Labels: area/elemental, kind/QA

#664 Revert "ci/e2e: increase default node number to 10"
  .github/workflows/master-e2e.yaml
Labels: area/elemental, kind/QA

#673 ci/e2e: disable upgrade tests
  .github/workflows/master-e2e.yaml
  tests/e2e/upgrade_test.go
Labels: area/elemental, kind/QA

#677 ci/ui: adapt cypress code to elem-ui 1.0.1
  .github/workflows/ui-e2e-k3s-stable.yaml
  .github/workflows/ui-e2e-rke2-stable.yaml
  tests/cypress/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/e2e/unit_tests/machine_selector.spec.ts
Labels: kind/QA, area/UI

#679 ci/ui: Disable upgrade
  tests/cypress/e2e/unit_tests/upgrade.spec.ts
Labels: kind/QA, area/UI

#682 Fix copyright and date range
  .obs/specfile/elemental.spec
  tests/cypress/e2e/unit_tests/advanced_filtering.spec.ts
  tests/cypress/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/e2e/unit_tests/first_connection.spec.ts
  tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/e2e/unit_tests/machine_selector.spec.ts
  tests/cypress/e2e/unit_tests/menu.spec.ts
  tests/cypress/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/e2e/unit_tests/user.spec.ts
  tests/cypress/plugins/index.ts
  tests/cypress/support/e2e.ts
  tests/cypress/support/elemental.ts
  tests/cypress/support/functions.ts
  tests/cypress/support/toplevelmenu.ts
  tests/e2e/bootstrap_test.go
  tests/e2e/configure_test.go
  tests/e2e/helpers/misc/misc.go
  tests/e2e/install_test.go
  tests/e2e/logs_test.go
  tests/e2e/suite_test.go
  tests/e2e/ui_test.go
  tests/e2e/upgrade_test.go
  tests/install/install_suite_test.go
  tests/install/install_test.go
  tests/smoke/smoke_suite_test.go
  tests/smoke/smoke_test.go
Labels: kind/QA, kind/chore

#681 ci/ui: add label functionality to Cypress tests
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e-k3s-latest.yaml
  .github/workflows/ui-e2e-k3s-obs-Dev.yaml
  .github/workflows/ui-e2e-k3s-obs-Stable.yaml
  .github/workflows/ui-e2e-k3s-obs-Staging.yaml
  .github/workflows/ui-e2e-k3s-stable.yaml
  .github/workflows/ui-e2e-rke2-latest.yaml
  .github/workflows/ui-e2e-rke2-obs-Dev.yaml
  .github/workflows/ui-e2e-rke2-obs-Stable.yaml
  .github/workflows/ui-e2e-rke2-obs-Staging.yaml
  .github/workflows/ui-e2e-rke2-stable.yaml
  tests/cypress/e2e/unit_tests/advanced_filtering.spec.ts
  tests/cypress/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/e2e/unit_tests/first_connection.spec.ts
  tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/e2e/unit_tests/machine_selector.spec.ts
  tests/cypress/e2e/unit_tests/menu.spec.ts
  tests/cypress/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/e2e/unit_tests/user.spec.ts
  tests/cypress/plugins/index.ts
  tests/cypress/support/filterTests.js
  tests/scripts/start-cypress-tests
Labels: kind/QA, area/UI

#684 ci/ui: update regex to check proxy logs
  tests/e2e/logs_test.go
Labels: kind/QA

#685 e2e: add separate upgrade test
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/e2e-k3s-latest.yaml
  .github/workflows/master-e2e.yaml
  README.md
  tests/assets/managedOSVersionChannel.yaml
  tests/assets/upgrade_skel.yaml
  tests/e2e/bootstrap_test.go
  tests/e2e/suite_test.go
  tests/e2e/upgrade_test.go
Labels: kind/QA

#688 ci/e2e: add regression test for elemental-operator#352
  tests/assets/selector.yaml
  tests/e2e/configure_test.go
Labels: kind/QA, area/elemental-operator

#689 ci/ui: fix ui upgrade tests names to match README
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  README.md
Labels: kind/QA
