Repository rancher/elemental, pull requests merged in 2023-10, with the labels that each got.

#1029 ci: fix operator uninstallation with RM Stable
  tests/e2e/uninstall-operator_test.go
Labels: kind/QA

#1033 ui/ci: fix labels and banner checks (#1032)
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1018 ci: use SeedImage for all CLI tests
  .github/workflows/cli-k3s-ibs_stable.yaml
  .github/workflows/cli-k3s-obs_dev.yaml
  .github/workflows/cli-k3s-obs_staging.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-k3s-rancher_latest.yaml
  .github/workflows/cli-k3s-rancher_stable.yaml
  .github/workflows/cli-k3s-sequential-rancher_latest.yaml
  .github/workflows/cli-k3s-sequential-rancher_stable.yaml
  .github/workflows/cli-obs-manual-workflow.yaml
  .github/workflows/cli-rke2-ibs_stable.yaml
  .github/workflows/cli-rke2-obs_dev.yaml
  .github/workflows/cli-rke2-obs_staging.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/cli-rke2-rancher_latest.yaml
  .github/workflows/cli-rke2-rancher_stable.yaml
  .github/workflows/cli-rke2-scalability-rancher_stable.yaml
  .github/workflows/cli-rke2-sequential-rancher_latest.yaml
  .github/workflows/cli-rke2-sequential-rancher_stable.yaml
  .github/workflows/master-e2e.yaml
  Makefile
  tests/Makefile
  tests/e2e/bootstrap_test.go
  tests/e2e/helpers/elemental/elemental.go
  tests/e2e/install_test.go
  tests/e2e/seedImage_test.go
  tests/e2e/suite_test.go
  tests/e2e/upgrade_test.go
  tests/scripts/get-name-from-managedosversion
Labels: kind/QA

#1037 ci: move github outputs step before ui tests
  .github/workflows/master-e2e.yaml
Labels: kind/QA

#1036 Remove build of artifacts
  .dockerignore
  .github/workflows/build-ci.yaml
  .github/workflows/build-iso-inject-pr.yaml
  .github/workflows/build-iso-pr.yaml
  .github/workflows/build-iso.yaml
  .github/workflows/image.yaml
  .github/workflows/integration.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/release.yaml
  .gitignore
  Dockerfile.image
  Dockerfile.iso
  Makefile
  iso/config
  iso/manifest.yaml
  tests/Makefile
  tests/assets/net-default.xml
  tests/e2e/helpers/network/network.go
  tests/install/install_suite_test.go
  tests/install/install_test.go
  tests/smoke/smoke_suite_test.go
  tests/smoke/smoke_test.go
Labels: area/automation, kind/QA, area/teal

#1044 ci: fix destroy_runner default value
  .github/workflows/cli-k3s-hardened-rancher_latest.yaml
  .github/workflows/cli-k3s-hardened-rancher_stable.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-k3s-rancher_latest.yaml
  .github/workflows/cli-k3s-rancher_stable.yaml
  .github/workflows/cli-k3s-sequential-rancher_latest.yaml
  .github/workflows/cli-k3s-sequential-rancher_stable.yaml
  .github/workflows/cli-rke2-hardened-rancher_latest.yaml
  .github/workflows/cli-rke2-hardened-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-rancher_latest.yaml
  .github/workflows/cli-rke2-rancher_stable.yaml
  .github/workflows/cli-rke2-scalability-rancher_stable.yaml
  .github/workflows/cli-rke2-sequential-rancher_latest.yaml
  .github/workflows/cli-rke2-sequential-rancher_stable.yaml
Labels: kind/QA

#1045 ci: fix destroy_runner default value - part 2
  .github/workflows/cli-k3s-hardened-rancher_latest.yaml
  .github/workflows/cli-k3s-hardened-rancher_stable.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-k3s-rancher_latest.yaml
  .github/workflows/cli-k3s-rancher_stable.yaml
  .github/workflows/cli-k3s-sequential-rancher_latest.yaml
  .github/workflows/cli-k3s-sequential-rancher_stable.yaml
  .github/workflows/cli-rke2-hardened-rancher_latest.yaml
  .github/workflows/cli-rke2-hardened-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-rancher_latest.yaml
  .github/workflows/cli-rke2-rancher_stable.yaml
  .github/workflows/cli-rke2-scalability-rancher_stable.yaml
  .github/workflows/cli-rke2-sequential-rancher_latest.yaml
  .github/workflows/cli-rke2-sequential-rancher_stable.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-k3s-rancher_latest.yaml
  .github/workflows/ui-k3s-rancher_stable.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-rke2-rancher_latest.yaml
  .github/workflows/ui-rke2-rancher_stable.yaml
Labels: kind/QA

#1054 ci/workflow: fix wrong variable type
  .github/workflows/cli-obs-manual-workflow.yaml
Labels: kind/QA

#1053 ci: fix github badges
  README.md
Labels: kind/QA

#1055 ci: fix github worklow names and README.md
  .github/workflows/cli-k3s-sequential-rm_stable.yaml
  .github/workflows/cli-rke2-hardened-rm_stable.yaml
  .github/workflows/cli-rke2-hardened-upgrade-reset-rm_stable.yaml
  README.md
Labels: kind/QA

#1057 ci: fix hardened test file name for GH badges
  README.md
Labels: kind/QA

#1062 ci/ui: fix for slem4r ISO
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1060 Multi-flavored OS build
  .obs/dockerfile/slem4r-flavored-os/Dockerfile
Labels: kind/enhancement, area/build

#1059 ci/ui: fix ui tests to run rancher 2.8
  tests/cypress/latest/e2e/unit_tests/advanced_filtering.spec.ts
  tests/cypress/latest/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_selector.spec.ts
  tests/cypress/latest/e2e/unit_tests/menu.spec.ts
  tests/cypress/latest/e2e/unit_tests/reset.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/e2e/unit_tests/user.spec.ts
  tests/cypress/latest/package.json
  tests/cypress/latest/support/utils.ts
Labels: kind/QA

#1071 Fix SLEM4R OS build
  .obs/dockerfile/slem4r-base-os/Dockerfile
  .obs/dockerfile/slem4r-flavored-os/Dockerfile
  .obs/dockerfile/slem4r-os/Dockerfile
Labels: kind/bug

#1067 ci: fix upgrade test with SLE Micro OS
  .github/workflows/cli-k3s-hardened-upgrade-reset-rm_head_2.7.yaml
  .github/workflows/cli-k3s-hardened-upgrade-reset-rm_head_2.8.yaml
  .github/workflows/cli-k3s-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade-rm_head_2.7.yaml
  .github/workflows/cli-k3s-os-upgrade-rm_head_2.8.yaml
  .github/workflows/cli-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-hardened-upgrade-reset-rm_head_2.7.yaml
  .github/workflows/cli-rke2-hardened-upgrade-reset-rm_head_2.8.yaml
  .github/workflows/cli-rke2-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade-rm_head_2.7.yaml
  .github/workflows/cli-rke2-os-upgrade-rm_head_2.8.yaml
  .github/workflows/cli-rke2-os-upgrade-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_stable.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
Labels: kind/QA

#1068 ci/ui: improve ui upgrade tests
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1073 ci: fix CLI upgrade tests
  tests/e2e/upgrade_test.go
Labels: kind/QA
