Repository rancher/elemental, pull requests merged in 2023-05, with the labels that each got.

#825 ci/ui: check embedded machineOsVersionChannel
  .github/workflows/master-e2e.yaml
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
Labels: kind/QA

#828 Ensure names are unique for all stages
  framework/files/system/oem/01_elemental-rootfs.yaml
Labels: kind/bug

#835 ci/ui: use RKE2 as upstream cluster for all RKE2 UI tests
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-rke2-obs_dev.yaml
  .github/workflows/ui-rke2-obs_stable.yaml
  .github/workflows/ui-rke2-obs_staging.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
  .github/workflows/ui-rke2-rancher_latest.yaml
  .github/workflows/ui-rke2-rancher_stable.yaml
  tests/cypress/latest/e2e/unit_tests/seed_image.spec.ts
  tests/cypress/latest/fixtures/myseedimage.yaml
  tests/cypress/latest/plugins/index.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA

#850 ci: install CRDs chart for operator when needed
  .github/workflows/cli-k3s-obs_dev.yaml
  .github/workflows/cli-k3s-obs_stable.yaml
  .github/workflows/cli-k3s-obs_staging.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-obs-manual-workflow.yaml
  .github/workflows/cli-rke2-obs_dev.yaml
  .github/workflows/cli-rke2-obs_stable.yaml
  .github/workflows/cli-rke2-obs_staging.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-k3s-obs_dev.yaml
  .github/workflows/ui-k3s-obs_stable.yaml
  .github/workflows/ui-k3s-obs_staging.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-obs_dev.yaml
  .github/workflows/ui-rke2-obs_stable.yaml
  .github/workflows/ui-rke2-obs_staging.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
  tests/e2e/install_test.go
  tests/e2e/suite_test.go
  tests/e2e/uninstall-operator_test.go
  tests/e2e/upgrade_test.go
Labels: kind/QA, area/elemental-operator
