Repository rancher/elemental, pull requests merged in 2023-08, with the labels that each got.

#914 Drop SLE Micro version references from code
  .obs/dockerfile/teal-iso/Dockerfile
  .obs/dockerfile/teal-os/Dockerfile
Labels: kind/chore

#942 Drop the need of the builder image, use the OS itself for that
  .obs/dockerfile/teal-iso/Dockerfile
Labels: need/discussion

#951 Fix elemental-register systemd service
  framework/files/usr/lib/systemd/system/elemental-register.service
Labels: kind/bug

#955 Fix elemental-iso-add-registratio script
  .github/elemental-iso-add-registration
Labels: kind/bug

#961 ci: fix RKE2 tests
  tests/e2e/bootstrap_test.go
Labels: kind/QA

#969 Use raspberrypi-firmware-uefi for Raspberry Pi
  .obs/dockerfile/slem4r-os/Dockerfile
Labels: area/arm, platform/raspberry

#970 ci/ui: fix ui upgrade workflow
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/commands.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA

#976 ci/ui: specify the branch to use for the UI
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/package.json
Labels: kind/QA

#979 ci: add manual trigger on some CLI workflows
  .github/workflows/cli-k3s-hardened-rancher_latest.yaml
  .github/workflows/cli-k3s-hardened-rancher_stable.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-k3s-rancher_latest.yaml
  .github/workflows/cli-k3s-rancher_stable.yaml
  .github/workflows/cli-rke2-hardened-rancher_latest.yaml
  .github/workflows/cli-rke2-hardened-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-rancher_latest.yaml
  .github/workflows/cli-rke2-rancher_stable.yaml
Labels: kind/QA

#983 Fix image/iso build
  .github/elemental-iso-build
  .obs/dockerfile/slem4r-os/Dockerfile
  .obs/dockerfile/teal-os/Dockerfile
  Dockerfile.image
  Dockerfile.iso
  Makefile
Labels: kind/QA

#985 ci: fix extract_kernel_init_squash
  Makefile
Labels: kind/QA

#986 ci: fix extract_kernel_init_squash - part 2
  Makefile
Labels: kind/QA

#987 ci: fix build image
  .github/workflows/image.yaml
  .github/workflows/master-e2e.yaml
  Makefile
Labels: kind/QA

#988 ci: fix ipxe boot
  Makefile
Labels: kind/QA

#991 ci: temporary workaround to fix upgrade to Staging
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
Labels: kind/QA
