Repository rancher/elemental, pull requests merged in 2023-04, with the labels that each got.

#773 ci/e2e: fix sporadic kubectl version issue
  tests/e2e/bootstrap_test.go
Labels: kind/QA

#777 ci/ui: test filtering with lower and upper case
  tests/cypress/latest/e2e/unit_tests/advanced_filtering.spec.ts
  tests/cypress/latest/fixtures/machine_inventory_1.yaml
Labels: kind/QA

#783 ci/ui: adapt to rancher 2.7.2 (latest stable)
  .github/workflows/ui-e2e-k3s-stable.yaml
  .github/workflows/ui-e2e-rke2-stable.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/support/elemental.ts
Labels: kind/QA

#789 ci/e2e: add cluster_type option to OBS tests
  .github/workflows/cli-obs-manual-workflow.yaml
  .github/workflows/e2e-k3s-obs-Dev.yaml
  .github/workflows/e2e-k3s-obs-Stable.yaml
  .github/workflows/e2e-k3s-obs-Staging.yaml
  .github/workflows/master-e2e.yaml
Labels: area/elemental, kind/QA

#790 ci: add workflow to test Qase triggering
  .github/workflows/qase-test.yaml
Labels: kind/QA

#791 ci: fix upgrade channel
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
Labels: area/elemental, kind/QA

#794 ci/e2e: use default version of backup-restore-operator
  .github/workflows/master-e2e.yaml
Labels: kind/QA

#796 ci/e2e: split backup/restore test
  tests/Makefile
  tests/e2e/backup-restore_test.go
Labels: kind/QA

#800 ci/ui: ability to install ui from official chart
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e-k3s-latest.yaml
  .github/workflows/ui-e2e-k3s-obs-Dev.yaml
  .github/workflows/ui-e2e-k3s-obs-Stable.yaml
  .github/workflows/ui-e2e-k3s-obs-Staging.yaml
  .github/workflows/ui-e2e-k3s-stable.yaml
  .github/workflows/ui-e2e-rke2-latest.yaml
  .github/workflows/ui-e2e-rke2-obs-Dev.yaml
  .github/workflows/ui-e2e-rke2-obs-Stable.yaml
  .github/workflows/ui-e2e-rke2-obs-Staging.yaml
  .github/workflows/ui-e2e-rke2-stable.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA

#814 ci/integ: fix failing test
  tests/install/install_test.go
Labels: kind/QA, area/elemental-cli

#813 812 several fixes for upgrade tests
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/support/functions.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA
