Repository rancher/elemental, pull requests merged in 2023-12, with the labels that each got.

#1119 ci/cli: use K3s for-scalability test
  .github/workflows/cli-k3s-scalability-rm_stable.yaml
  README.md
Labels: kind/QA

#1121 ci/cli: fix RKE2 multi-cluster
  .github/workflows/cli-rke2-multi_cluster-rm_stable.yaml
Labels: kind/QA

#1120 ci/ui: update html selector for Cypress
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1124 ci/cli: fix OBS Staging tests
  .github/workflows/cli-k3s-obs_staging.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-obs_staging.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
Labels: kind/QA

#1126 ci/cli: fix upgrade to Staging tests
  .github/workflows/cli-k3s-obs_staging.yaml
  .github/workflows/cli-rke2-obs_staging.yaml
  tests/scripts/get-name-from-managedosversion
Labels: kind/QA

#1129 ci: add device-selector test
  tests/assets/machineRegistration.yaml
  tests/scripts/install-vm
Labels: kind/QA

#1130 Mkdir /host/run/elemental in suc-upgrade
  framework/files/usr/sbin/suc-upgrade
Labels: kind/bug

#1131 Revert to 'old' RPi firmware
  .obs/dockerfile/slem-base-os/Dockerfile
Labels: area/arm, platform/raspberry

#1127 ci/ui: automate ui-extension upgrade
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_stable.yaml
  tests/cypress/latest/e2e/unit_tests/upgrade-ui-extension.spec.ts
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1134 ci/ui: upgrade elemental operator via marketplace
  .github/workflows/master-e2e.yaml
  tests/cypress/latest/e2e/unit_tests/upgrade-operator.spec.ts
Labels: kind/QA
