Repository rancher/elemental, pull requests merged in 2023-01, with the labels that each got.

#603 ci/ui: fix permissions for 'downloads' directory #2
  .github/workflows/master-e2e.yaml
Labels: kind/QA

#607 Update gitignore file
  .gitignore
Labels: kind/QA

#615 ci/e2e: fix path to upgrade image
  tests/assets/osVersions.json
Labels: area/elemental, kind/QA, area/upgrade

#617 ci/integ: fix failing test
  tests/install/install_test.go
Labels: kind/QA, area/elemental-cli

#618 e2e ui: show k8s deprecated versions
  tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
Labels: kind/QA

#621 e2e ui: change how we check that an app is deleted
  tests/cypress/e2e/unit_tests/deploy_app.spec.ts
Labels: kind/QA

#630 ci/e2e: don't run test on latest RM on every push
  .github/workflows/e2e-k3s-latest.yaml
  .github/workflows/e2e-rke2-latest.yaml
Labels: kind/QA

#636 e2e/ui: replace .xterm-cursor-layer in Cypress
  tests/cypress/e2e/unit_tests/upgrade.spec.ts
Labels: kind/QA
