Repository rancher/elemental, pull requests merged in 2023-03, with the labels that each got.

#703 ci/ui: remove user workaround in RKE tests
  .github/workflows/ui-e2e-rke2-latest.yaml
  .github/workflows/ui-e2e-rke2-obs-Dev.yaml
  .github/workflows/ui-e2e-rke2-obs-Stable.yaml
  .github/workflows/ui-e2e-rke2-obs-Staging.yaml
  .github/workflows/ui-e2e-rke2-stable.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
Labels: kind/QA, area/UI

#710 ci/ui: add test to upgrade via os version channel
  .github/workflows/master-e2e.yaml
  tests/cypress/e2e/unit_tests/upgrade.spec.ts
Labels: kind/QA, area/UI

#704 ci/e2e: fix/reduce OOM killer issue in CI with lot of nodes
  tests/scripts/install-vm
Labels: area/elemental, kind/QA

#715 ci/e2e: fix emulated TPM
  .github/workflows/master-e2e.yaml
  tests/e2e/bootstrap_test.go
Labels: kind/QA, area/elemental-operator

#716 ci/ui: Test embedded hardware labels
  tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/fixtures/custom_cloud-config.yaml
  tests/cypress/support/e2e.ts
  tests/cypress/support/functions.ts
Labels: kind/QA, area/UI

#719 ci/ui: Workaround in delete machine reg test
  tests/cypress/support/functions.ts
Labels: kind/QA

#725 ci: add worflow to manually trigger a test
  .github/workflows/cli-obs-manual-workflow.yaml
Labels: area/elemental, kind/QA, area/elemental-operator

#739 ci/ui: increase timeout when checking cluster
  tests/cypress/e2e/unit_tests/machine_inventory.spec.ts
Labels: kind/QA, area/UI

#743 ui/ci: increase timeout when creating RKE2 cluster
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
Labels: kind/QA

#746 ci: bump k3s to v1.24.11+k3s1
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-sequential-rancher_latest.yaml
  .github/workflows/e2e-k3s-latest.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-e2e-k3s-latest.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml
Labels: kind/QA

#748 ci: debug hardened cluster issue
  tests/e2e/configure_test.go
Labels: kind/QA

#760 ci: use public dns as hostname
  .github/workflows/cli-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-obs-manual-workflow.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/cli-rke2-os-upgrade-rancher_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/master-e2e.yaml
  tests/e2e/suite_test.go
  tests/scripts/config-private-ca
Labels: kind/QA

#759 ci/e2e: don't test operator uninstallation on Stable
  .github/workflows/master-e2e.yaml
Labels: kind/QA, area/elemental-operator

#754 ci/ui: test ISO building feature
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/support/e2e.ts
  tests/cypress/latest/support/functions.ts
  tests/e2e/ui_test.go
  tests/scripts/start-cypress-tests
Labels: kind/QA, area/UI

#763 e2e/ui: Make sure we can bind a cluster to only one upgrade group at a time
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
Labels: kind/QA

#767 ci/e2e: small fix for CA test
  tests/e2e/install_test.go
Labels: kind/QA

#770 ci/e2e: fix Cluster structure
  tests/e2e/helpers/misc/misc.go
Labels: kind/QA
