Repository rancher/elemental, pull requests merged in 2023-07, with the labels that each got.

#898 Fix proxy issue with rancher head
  .github/workflows/master-e2e.yaml
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/utils.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA

#900 ci/ui: use ISO in upgrade scenario
  .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml
  tests/scripts/start-cypress-tests
Labels: kind/QA

#896 Switch supportlevel to "l3"
  .obs/dockerfile/teal-iso/Dockerfile
  .obs/dockerfile/teal-os/Dockerfile
Labels: kind/chore, area/build

#904 ui/ci: never boot from dev iso in upgrade tests
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#890 Run elemental register at each boot
  framework/files/system/oem/99_elemental-register.yaml
  framework/files/usr/lib/systemd/system/elemental-register.service
Labels: status/blocked

#899 ci/ui: split rancher functions into separate file
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-k3s-os-upgrade-rancher_stable.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_latest.yaml
  .github/workflows/ui-rke2-os-upgrade-rancher_stable.yaml
  tests/cypress/latest/e2e/unit_tests/advanced_filtering.spec.ts
  tests/cypress/latest/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/e2e/unit_tests/first_connection.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_selector.spec.ts
  tests/cypress/latest/e2e/unit_tests/menu.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/e2e/unit_tests/user.spec.ts
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/e2e.ts
  tests/cypress/latest/support/elemental.ts
  tests/cypress/latest/support/rancher.ts
  tests/cypress/latest/support/toplevelmenu.ts
  tests/cypress/latest/support/utils.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA

#908 ci: fix README.md test file generation
  tests/scripts/generate-readme
  tests/scripts/generate-tests-description
Labels: kind/QA

#907 ci: add hardened cluster in obs tests
  .github/workflows/cli-k3s-hardened-rancher_latest.yaml
  .github/workflows/cli-k3s-hardened-rancher_stable.yaml
  .github/workflows/master-e2e.yaml
  tests/scripts/config-hardened
Labels: kind/QA

#913 ci/ui: try to use my new npm package
  tests/cypress/latest/.npmrc
  tests/cypress/latest/e2e/unit_tests/advanced_filtering.spec.ts
  tests/cypress/latest/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/e2e/unit_tests/first_connection.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_selector.spec.ts
  tests/cypress/latest/e2e/unit_tests/menu.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/e2e/unit_tests/user.spec.ts
  tests/cypress/latest/package.json
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/e2e.ts
  tests/cypress/latest/support/elemental.ts
  tests/cypress/latest/support/rancher.ts
  tests/cypress/latest/tsconfig.json
Labels: kind/QA

#925 ci: ignore case distinctions for grep command
  tests/e2e/bootstrap_test.go
Labels: kind/QA

#930 e2e/ui: bump cypress library to 1.0.6
  tests/cypress/latest/package.json
Labels: kind/QA

#931 ci: fix sporadic issue during rollout check
  tests/e2e/app_test.go
  tests/e2e/upgrade_test.go
Labels: kind/QA

#932 ci/ui: use QASE reporting tool
  .github/workflows/cli-k3s-obs_dev.yaml
  .github/workflows/cli-k3s-obs_stable.yaml
  .github/workflows/cli-k3s-obs_staging.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-obs_dev.yaml
  .github/workflows/cli-rke2-obs_stable.yaml
  .github/workflows/cli-rke2-obs_staging.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/master-e2e.yaml
  .github/workflows/ui-k3s-obs_dev.yaml
  .github/workflows/ui-k3s-obs_stable.yaml
  .github/workflows/ui-k3s-obs_staging.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-obs_dev.yaml
  .github/workflows/ui-rke2-obs_stable.yaml
  .github/workflows/ui-rke2-obs_staging.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
  tests/cypress/latest/cypress.config.ts
  tests/cypress/latest/e2e/unit_tests/advanced_filtering.spec.ts
  tests/cypress/latest/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/e2e/unit_tests/first_connection.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_selector.spec.ts
  tests/cypress/latest/e2e/unit_tests/menu.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/e2e/unit_tests/user.spec.ts
  tests/cypress/latest/package.json
  tests/scripts/start-cypress-tests
Labels: kind/QA
