Repository rancher/elemental, pull requests merged in 2024-02, with the labels that each got.

#1194 ci/cli: fix regression on operator installation
  tests/e2e/install_test.go
Labels: kind/QA

#1196 Make ibs happy - provide BuildName in Dockerfiles
  .obs/dockerfile/slem-base-iso/Dockerfile
  .obs/dockerfile/slem-base-os/Dockerfile
  .obs/dockerfile/slem-iso/Dockerfile
  .obs/dockerfile/slem-os/Dockerfile
Labels: area/dependencies, area/build

#1198 ci: fix Qase report publishing
  .github/workflows/master_e2e.yaml
Labels: kind/QA

#1201 fix URL in spec
  .obs/specfile/elemental.spec
Labels: area/build

#1200 ci/ui: clean code for 1.3.0 UI
  tests/cypress/latest/e2e/unit_tests/upgrade-ui-extension.spec.ts
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1191 Add back recovery hostname
  framework/files/system/oem/03_branding.yaml
Labels: kind/bug

#1211 ci/ui: fix extension installation
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/package.json
Labels: kind/QA

#1215 ci/ui: deploy elemental operator when using RM2.7
  tests/cypress/latest/e2e/unit_tests/elemental_operator.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/support/elemental.ts
Labels: kind/QA

#1214 ci: fix upgrade with OSVersionName/OSVersionChannel
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_test_choice.yaml
Labels: kind/QA

#1217 ci: fix multi-cluster test
  .github/workflows/cli-k3s-multi_cluster-rm_stable.yaml
  .github/workflows/cli-rke2-multi_cluster-rm_stable.yaml
  tests/Makefile
  tests/e2e/install_test.go
  tests/e2e/multi-cluster_test.go
  tests/e2e/suite_test.go
Labels: kind/QA

#1220 ci: fix scalability test
  tests/e2e/suite_test.go
Labels: kind/QA

#1228 ci: fix manual OBS workflow
  .github/workflows/cli-obs-manual-workflow.yaml
Labels: kind/QA

#1227 ci: fix Rancher Manager upgrade
  .github/workflows/cli-k3s-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade-rm_stable.yaml
  tests/e2e/airgap_test.go
  tests/e2e/app_test.go
  tests/e2e/suite_test.go
  tests/go.mod
  tests/go.sum
Labels: kind/QA

#1229 ci: use new kubectl.RunWithoutErr function
  tests/e2e/app_test.go
  tests/e2e/backup-restore_test.go
  tests/e2e/bootstrap_test.go
  tests/e2e/helpers/elemental/elemental.go
  tests/e2e/install_test.go
  tests/e2e/logs_test.go
  tests/e2e/multi-cluster_test.go
  tests/e2e/reset_test.go
  tests/e2e/seedImage_test.go
  tests/e2e/suite_test.go
  tests/e2e/ui_test.go
  tests/e2e/uninstall-operator_test.go
  tests/e2e/upgrade_test.go
Labels: kind/QA

#1231 ci/airgap: fix build and deploy scripts
  .github/workflows/cli-k3s-airgap_rm_latest_dev.yaml
  .github/workflows/cli-k3s-airgap_rm_stable.yaml
  tests/Makefile
  tests/e2e/airgap_test.go
  tests/e2e/seedImage_test.go
  tests/e2e/suite_test.go
  tests/scripts/build-airgap
  tests/scripts/deploy-airgap
Labels: kind/QA

#1240 ci/ui: enable media build select
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1245 ci/airgap: add retry commands for helm and skopeo
  tests/scripts/build-airgap
  tests/scripts/deploy-airgap
Labels: kind/QA

#1244 ci/ui: add test for dhcp hostname
  tests/assets/machineRegistration-multi.yaml
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/latest/fixtures/custom_cloud-config_with_reset.yaml
Labels: kind/QA

#1251 ci/ui: add workaround for dhcp test
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
Labels: kind/QA

#1247 ci: fix backup-restore-operator tests
  .github/actions/logs-and-summary/action.yaml
  .github/workflows/cli-k3s-hardened-rm_head_2.7.yaml
  .github/workflows/cli-k3s-hardened-rm_head_2.8.yaml
  .github/workflows/cli-k3s-hardened-rm_head_2.9.yaml
  .github/workflows/cli-k3s-reset-rm_head_2.7.yaml
  .github/workflows/cli-k3s-reset-rm_head_2.8.yaml
  .github/workflows/cli-k3s-reset-rm_head_2.9.yaml
  .github/workflows/cli-k3s-rm_head_2.7.yaml
  .github/workflows/cli-k3s-rm_head_2.8.yaml
  .github/workflows/cli-k3s-rm_head_2.9.yaml
  .github/workflows/sub_cli.yaml
Labels: kind/QA

#1253 ci: bump ele-testhelpers library
  tests/go.mod
  tests/go.sum
Labels: kind/QA

#1252 ci: fix container paths in upgrade tests
  .github/workflows/cli-k3s-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_stable.yaml
Labels: kind/QA

#1254 ci: use correct container path for upgrade tests
  .github/workflows/cli-k3s-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_stable.yaml
Labels: kind/QA

#1257 Revert "ci/ui: add workaround for dhcp test"
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
Labels: kind/QA
