Repository rancher/elemental, pull requests merged in 2024-09, with the labels that each got.

#1546 ci: add clearer status in summary
  .github/actions/logs-and-summary/action.yaml
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_airgap.yaml
  .github/workflows/sub_cli.yaml
Labels: kind/QA, area/CI

#1548 ci/cli: add localstorage+MetalLB in RKE2 tests
  .github/workflows/sub_cli.yaml
  tests/assets/local-storage.yaml
  tests/assets/metallb_rsc.yaml
  tests/assets/net-default-airgap.xml
  tests/assets/net-default.xml
  tests/e2e/app_test.go
  tests/e2e/suite_test.go
Labels: kind/QA

#1552 ci/ui: refactor all Cypress code
  tests/cypress/latest/e2e/unit_tests/advanced_filtering.spec.ts
  tests/cypress/latest/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_operator.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_selector.spec.ts
  tests/cypress/latest/e2e/unit_tests/menu.spec.ts
  tests/cypress/latest/e2e/unit_tests/os_version.spec.ts
  tests/cypress/latest/e2e/unit_tests/reset.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade-operator.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade-ui-extension.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/e2e/unit_tests/user.spec.ts
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/elemental.ts
Labels: kind/QA

#1553 ci/ui: add global slowdown for cypress tests
  tests/cypress/latest/e2e/unit_tests/advanced_filtering.spec.ts
  tests/cypress/latest/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_operator.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/e2e/unit_tests/first_connection.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_inventory.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_registration.spec.ts
  tests/cypress/latest/e2e/unit_tests/machine_selector.spec.ts
  tests/cypress/latest/e2e/unit_tests/os_version.spec.ts
  tests/cypress/latest/e2e/unit_tests/reset.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade-operator.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade-ui-extension.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/support/e2e.ts
Labels: kind/QA

#1562 Switch to git in OBS
  .obs/dockerfile/SL-Micro-baremetal-container/Dockerfile
  .obs/dockerfile/SL-Micro-baremetal-container/_service
  .obs/dockerfile/SL-Micro-base-container/Dockerfile
  .obs/dockerfile/SL-Micro-base-container/_service
  .obs/dockerfile/SL-Micro-k3s-selinux-container/Dockerfile
  .obs/dockerfile/SL-Micro-k3s-selinux-container/_service
  .obs/dockerfile/SL-Micro-kvm-container/Dockerfile
  .obs/dockerfile/SL-Micro-kvm-container/_service
  .obs/dockerfile/SL-Micro-rke2-selinux-container/Dockerfile
  .obs/dockerfile/SL-Micro-rke2-selinux-container/_service
  .obs/dockerfile/SL-Micro-rt-container/Dockerfile
  .obs/dockerfile/SL-Micro-rt-container/_service
  .obs/dockerfile/build-baremetal-iso-image/Dockerfile
  .obs/dockerfile/build-baremetal-iso-image/_service
  .obs/dockerfile/build-baremetal-iso-image/manifest.yaml
  .obs/dockerfile/build-base-iso-image/Dockerfile
  .obs/dockerfile/build-base-iso-image/_service
  .obs/dockerfile/build-base-iso-image/manifest.yaml
  .obs/dockerfile/build-k3s-selinux-iso-image/Dockerfile
  .obs/dockerfile/build-k3s-selinux-iso-image/_service
  .obs/dockerfile/build-k3s-selinux-iso-image/manifest.yaml
  .obs/dockerfile/build-kvm-iso-image/Dockerfile
  .obs/dockerfile/build-kvm-iso-image/_service
  .obs/dockerfile/build-kvm-iso-image/manifest.yaml
  .obs/dockerfile/build-rke2-selinux-iso-image/Dockerfile
  .obs/dockerfile/build-rke2-selinux-iso-image/_service
  .obs/dockerfile/build-rke2-selinux-iso-image/manifest.yaml
  .obs/dockerfile/build-rt-iso-image/Dockerfile
  .obs/dockerfile/build-rt-iso-image/_service
  .obs/dockerfile/build-rt-iso-image/manifest.yaml
  .obs/specfile/elemental-rpmlintrc
  .obs/specfile/elemental/elemental-rpmlintrc
  .obs/specfile/elemental/elemental.spec
Labels: area/build

#1573 ci: bump helpers libraries
  tests/go.mod
  tests/go.sum
Labels: kind/QA

#1571 ci/ui: add git repo input in marketplace tests
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_test_choice.yaml
  .github/workflows/sub_ui.yaml
  .github/workflows/ui-marketplace-workflow.yaml
  tests/cypress/latest/e2e/unit_tests/elemental_operator.spec.ts
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/elemental.ts
  tests/cypress/latest/support/utils.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA

#1575 Fix UI CI for 1.6.4 stable
  tests/cypress/latest/e2e/unit_tests/first_connection.spec.ts
Labels: kind/QA

#1577 ci/cli: fix OS upgrade test
  .github/workflows/sub_cli.yaml
  tests/e2e/install_test.go
  tests/e2e/uninstall-operator_test.go
  tests/e2e/upgrade_test.go
Labels: kind/QA

#1579 ci/ui: increase timeout when checking machine inv
  tests/cypress/latest/e2e/unit_tests/reset.spec.ts
Labels: kind/QA

#1561 ci/cli: add full backup/restore test
  .github/workflows/SCHEDULING.md
  .github/workflows/cli-full-backup-restore-matrix.yaml
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_cli.yaml
  .github/workflows/sub_test_choice.yaml
  README.md
  tests/Makefile
  tests/assets/restore.yaml
  tests/e2e/backup-restore_test.go
  tests/e2e/install_test.go
  tests/e2e/suite_test.go
  tests/e2e/upgrade_test.go
Labels: kind/QA

#1587 ci: don't check app after operator uninstallation
  .github/workflows/sub_cli.yaml
Labels: kind/QA

#1588 ci/ui: install operator from cli for ui upgrade
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_cli.yaml
  .github/workflows/sub_multi.yaml
  .github/workflows/sub_test_choice.yaml
  .github/workflows/sub_ui.yaml
  .github/workflows/ui-k3s-ibs_stable.yaml
  .github/workflows/ui-k3s-matrix.yaml
  .github/workflows/ui-k3s-obs_dev.yaml
  .github/workflows/ui-k3s-obs_staging.yaml
  .github/workflows/ui-k3s-upgrade-matrix.yaml
  .github/workflows/ui-marketplace-upgrade-workflow.yaml
  .github/workflows/ui-marketplace-workflow.yaml
  .github/workflows/ui-rke2-ibs_stable.yaml
  .github/workflows/ui-rke2-matrix.yaml
  .github/workflows/ui-rke2-obs_dev.yaml
  .github/workflows/ui-rke2-obs_staging.yaml
  .github/workflows/ui-rke2-upgrade-matrix.yaml
  tests/cypress/latest/e2e/unit_tests/elemental_operator.spec.ts
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/utils.ts
  tests/e2e/install_test.go
  tests/e2e/suite_test.go
  tests/scripts/start-cypress-tests
Labels: kind/QA

#1594 ci/cli: fix sporadic timeouts in uninstall-operator
  tests/e2e/uninstall-operator_test.go
Labels: kind/QA

#1595 ci/ui: fix rke2 prime test
  tests/cypress/latest/support/elemental.ts
Labels: kind/QA

#1593 ci: add better pod status check
  tests/e2e/airgap_test.go
  tests/e2e/suite_test.go
  tests/e2e/upgrade_test.go
  tests/go.mod
  tests/go.sum
Labels: kind/QA

#1597 ci/cli: fix 2.8-head test
  .github/workflows/cli-rm-head-2.8-matrix.yaml
Labels: kind/QA

#1596 ci/ui: fix upgrade cloud-config file
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/fixtures/custom_cloud-config_upgrade.yaml
  tests/cypress/latest/fixtures/custom_cloud-config_with_reset.yaml
Labels: kind/QA

#1591 ci/airgap: fix test with Dev operator
  tests/e2e/seedImage_test.go
  tests/e2e/suite_test.go
  tests/e2e/uninstall-operator_test.go
  tests/scripts/build-airgap
  tests/scripts/deploy-chartmuseum
Labels: kind/QA

#1601 ci/ui: use rke2 as upstream cluster in rke2 tests
  .github/workflows/ui-rke2-obs_dev.yaml
  .github/workflows/ui-rke2-obs_staging.yaml
  .github/workflows/ui-rke2-upgrade-matrix.yaml
Labels: kind/QA
