Repository rancher/elemental, pull requests merged in 2024-07, with the labels that each got.

#1472 ci/ui: fix dev channel for upgrade test
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1473 ci/airgap: fix os channel sync with Dev
  tests/scripts/build-airgap
Labels: kind/QA

#1475 ci/ui: automate latest os version selection
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/commands.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA

#1480 ci/scalability: remove test on Rancher Manager Devel
  .github/workflows/cli-k3s-scalability-matrix.yaml
Labels: kind/QA, area/scalability

#1481 ci: remove EndBug/add-and-commit action
  .github/workflows/update-tests-description.yaml
Labels: kind/QA, area/CI

#1483 ci: fix mulicluster test
  .github/workflows/cli-multicluster-matrix.yaml
  tests/e2e/multi-cluster_test.go
Labels: kind/QA

#1484 ci/airgap: fix test with Rancher Manager Stable
  tests/scripts/build-airgap
Labels: kind/QA, area/airgap

#1485 ci: fix deployed application test
  .github/workflows/sub_cli.yaml
Labels: kind/QA

#1486 ci/multicluster: reduce number of tested cluster
  .github/workflows/cli-multicluster-matrix.yaml
Labels: kind/QA

#1482 ci/ui: adapt code for basic rancher 2.9 test
  tests/cypress/latest/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1488 ci/cli: use Rancher Manager Prime on RKE2 tests
  .github/workflows/cli-rke2-ibs_stable.yaml
  .github/workflows/cli-rke2-matrix.yaml
  .github/workflows/cli-rke2-obs_dev.yaml
  .github/workflows/cli-rke2-obs_staging.yaml
  .github/workflows/cli-rke2-upgrade-matrix.yaml
Labels: kind/QA

#1489 ci: add a 2nd HDD
  tests/scripts/install-vm
Labels: kind/QA

#1490 ci: use latest version of DeployRancherManager func
  tests/go.mod
  tests/go.sum
Labels: kind/QA

#1492 ci/cli: test recovery mode after OS upgrade
  tests/e2e/bootstrap_test.go
  tests/e2e/upgrade_test.go
Labels: kind/QA

#1493 ci/cli: add Regression tests
  .github/workflows/SCHEDULING.md
  .github/workflows/cli-regression-matrix.yaml
  README.md
Labels: kind/QA

#1495 ci/ui: enable prime and rancher 2.9-head in UI
  .github/workflows/sub_ui.yaml
  .github/workflows/ui-k3s-matrix.yaml
  .github/workflows/ui-k3s-upgrade-matrix.yaml
  .github/workflows/ui-rke2-matrix.yaml
  .github/workflows/ui-rke2-upgrade-matrix.yaml
  .github/workflows/ui-rm-head-2.9-matrix.yaml
  README.md
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade-ui-extension.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/elemental.ts
  tests/cypress/latest/support/utils.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA

#1505 ci/ui: add weekly rancher 2.7 head tests
  .github/workflows/ui-rm-head-2.7-matrix.yaml
  README.md
Labels: kind/QA

#1507 ci/ui: Force elemental ui rc7 for 2.9
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
Labels: kind/QA

#1508 ci/openqa: update Job Group definition
  tests/assets/openqa_elemental_jobgroup.yaml
  tests/assets/openqa_elemental_updates_jobgroup.yaml
Labels: kind/QA

#1510 ci/ui: Do not install rc ui version in 2.9 upgrade
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
Labels: kind/QA, area/CI
