Repository rancher/elemental, pull requests merged in 2024-10, with the labels that each got.

#1602 ci/ui: test download button from seed image menu
  .github/workflows/sub_ui.yaml
  tests/cypress/latest/e2e/unit_tests/seed_image.spec.ts
Labels: kind/QA

#1603 ci/ui: remove useless dash in check_os_version
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
Labels: kind/QA

#1607 ci/openqa: fix QAM tests
  tests/assets/openqa_elemental_updates_jobgroup.yaml
Labels: kind/QA

#1609 ci/ui: add upgrade group delete test
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
Labels: kind/QA

#1615 ci: add time to live for GCP secrets
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_clean-and-delete-runner.yaml
  .github/workflows/sub_create-runner.yaml
Labels: kind/QA

#1610 ci/ui: use os_to_test in UI manual workflows
  .github/workflows/cli-obs-manual-workflow.yaml
  .github/workflows/sub_ui.yaml
  .github/workflows/ui-obs-manual-upgrade-workflow.yaml
  .github/workflows/ui-obs-manual-workflow.yaml
  tests/Makefile
  tests/cypress/latest/e2e/unit_tests/elemental_plugin.spec.ts
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/commands.ts
  tests/cypress/latest/support/utils.ts
  tests/scripts/deploy-chartmuseum
  tests/scripts/start-cypress-tests
Labels: kind/QA

#1621 ci/cli: fix migration test with RKE2
  .github/workflows/cli-full-backup-restore-matrix.yaml
  tests/e2e/suite_test.go
Labels: kind/QA

#1624 ci: remove rancher 2.7 tests
  .github/workflows/SCHEDULING.md
  .github/workflows/cli-rm-head-2.7-matrix.yaml
  .github/workflows/ui-rm-head-2.7-matrix.yaml
  README.md
  tests/cypress/latest/e2e/unit_tests/elemental_operator.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade-operator.spec.ts
  tests/cypress/latest/e2e/unit_tests/upgrade.spec.ts
Labels: kind/QA

#1631 ci: no need to run clean-delete if we want to keep the runner
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_clean-and-delete-runner.yaml
Labels: area/CI

#1632 ci/ui: remove useless else condition in upgrade
  tests/cypress/latest/e2e/unit_tests/upgrade-operator.spec.ts
Labels: kind/QA

#1633 ci/cli: fix regression test
  .github/workflows/cli-regression-matrix.yaml
Labels: kind/QA

#1635 ci/ui: fix operator upgrade for rancher 2.8
  tests/cypress/latest/e2e/unit_tests/upgrade-operator.spec.ts
Labels: kind/QA

#1614 Remove no longer valid OBS workflow
  .obs/workflows.yml
Labels: kind/chore

#1637 ci/cli: fix manual workflow
  .github/workflows/cli-obs-manual-workflow.yaml
Labels: kind/QA
