Repository rancher/elemental, pull requests merged in 2024-05, with the labels that each got.

#1396 Drop unused accounting.yaml
  framework/files/system/oem/04_accounting.yaml
Labels: kind/chore

#1404 Set layout with yaml format
  framework/files/system/oem/01_elemental-rootfs.yaml
Labels: kind/enhancement

#1405 Fix grub2-x86_64-efi installation
  .obs/dockerfile/micro-base-os/Dockerfile
Labels: kind/bug, kind/backport

#1407 Fix grub2-x86_64-efi installation
  .obs/dockerfile/micro-base-os/Dockerfile
Labels: kind/bug, kind/backport

#1406 Fix grub2-x86_64-efi installation
  .obs/dockerfile/slem-base-os/Dockerfile
Labels: kind/bug, kind/backport

#1408 Removing syslinux from base image
  .obs/dockerfile/micro-base-os/Dockerfile
Labels: kind/enhancement

#1412 ci/ui: enable user account back
  .github/workflows/ui-obs-manual-upgrade-workflow.yaml
  .github/workflows/ui-rke2-ibs_stable.yaml
  .github/workflows/ui-rke2-matrix.yaml
  .github/workflows/ui-rke2-obs_dev.yaml
  .github/workflows/ui-rke2-obs_staging.yaml
  .github/workflows/ui-rke2-upgrade-matrix.yaml
Labels: kind/QA

#1411 ci/cli: upgrade Rancher Manager only to 2.8.x
  .github/workflows/cli-k3s-upgrade-matrix.yaml
  .github/workflows/cli-rke2-upgrade-matrix.yaml
  tests/e2e/upgrade_test.go
Labels: kind/QA

#1419 ci/ui: bump Cypress container to 13.9.0
  .github/workflows/sub_ui.yaml
  tests/cypress/latest/cypress.config.ts
Labels: kind/QA

#1397 ci/openqa: update jobgroup for SLMicro 6.0
  tests/assets/openqa_elemental_jobgroup.yaml
Labels: kind/QA

#1420 ci: add badge for CLI-K3s-Downgrade test
  README.md
Labels: kind/QA

#1422 ci/cli: fix multicluster test
  .github/workflows/cli-multicluster-matrix.yaml
Labels: kind/QA

#1427 ci/weekly: fix Rancher latest/devel installation
  .github/workflows/cli-k3s-airgap-matrix.yaml
  .github/workflows/cli-k3s-scalability-matrix.yaml
  .github/workflows/cli-multicluster-matrix.yaml
Labels: kind/QA

#1426 ci/cli: fix operator uninstallation test
  tests/e2e/uninstall-operator_test.go
Labels: kind/QA

#1424 ci: bump k8s upstream/downstream to latest 1.27.13
  .github/workflows/cli-k3s-airgap-matrix.yaml
  .github/workflows/cli-k3s-downgrade-matrix.yaml
  .github/workflows/cli-k3s-ibs_stable.yaml
  .github/workflows/cli-k3s-matrix.yaml
  .github/workflows/cli-k3s-obs_dev.yaml
  .github/workflows/cli-k3s-obs_staging.yaml
  .github/workflows/cli-k3s-scalability-matrix.yaml
  .github/workflows/cli-k3s-upgrade-matrix.yaml
  .github/workflows/cli-multicluster-matrix.yaml
  .github/workflows/cli-obs-manual-upgrade-workflow.yaml
  .github/workflows/cli-obs-manual-workflow.yaml
  .github/workflows/cli-rke2-ibs_stable.yaml
  .github/workflows/cli-rke2-matrix.yaml
  .github/workflows/cli-rke2-obs_dev.yaml
  .github/workflows/cli-rke2-obs_staging.yaml
  .github/workflows/cli-rke2-upgrade-matrix.yaml
  .github/workflows/ui-k3s-ibs_stable.yaml
  .github/workflows/ui-k3s-matrix.yaml
  .github/workflows/ui-k3s-obs_dev.yaml
  .github/workflows/ui-k3s-obs_staging.yaml
  .github/workflows/ui-k3s-upgrade-matrix.yaml
  .github/workflows/ui-marketplace-upgrade-workflow.yaml
  .github/workflows/ui-marketplace-workflow.yaml
  .github/workflows/ui-obs-manual-upgrade-workflow.yaml
  .github/workflows/ui-obs-manual-workflow.yaml
  .github/workflows/ui-rke2-ibs_stable.yaml
  .github/workflows/ui-rke2-matrix.yaml
  .github/workflows/ui-rke2-obs_dev.yaml
  .github/workflows/ui-rke2-obs_staging.yaml
  .github/workflows/ui-rke2-upgrade-matrix.yaml
Labels: kind/QA

#1431 ci/cli: fix IPv6 deactivation
  tests/assets/machineRegistration-multi.yaml
  tests/assets/machineRegistration.yaml
Labels: kind/QA

#1430 ci/cli: add a SELinux OS image test
  .github/workflows/SCHEDULING.md
  .github/workflows/cli-k3s-selinux-matrix.yaml
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_cli.yaml
  .github/workflows/sub_test_choice.yaml
  README.md
  tests/Makefile
  tests/assets/cluster.yaml
  tests/assets/machineRegistration-multi.yaml
  tests/assets/machineRegistration.yaml
  tests/assets/seedImage-multi.yaml
  tests/assets/seedImage.yaml
  tests/cypress/latest/fixtures/custom_cloud-config.yaml
  tests/cypress/latest/fixtures/custom_cloud-config_with_reset.yaml
  tests/e2e/configure_test.go
  tests/e2e/seedImage_test.go
  tests/e2e/suite_test.go
Labels: kind/QA

#1442 ci: Bump checkout version in update-tests-description
  .github/workflows/update-tests-description.yaml
Labels: kind/QA
