Repository rancher/elemental, pull requests merged in 2024-03, with the labels that each got.

#1260 ci: validate that the operator cannot be reinstalled
  tests/e2e/uninstall-operator_test.go
Labels: kind/QA

#1269 ci/ui: update operator workaround in ui deployment
  tests/cypress/latest/support/elemental.ts
Labels: kind/QA

#1277 ci: allow root login by SSH
  tests/assets/machineRegistration.yaml
Labels: area/CI

#1286 ci: use Elemental sle-micro-6.0 based images
  .github/workflows/cli-k3s-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_stable.yaml
Labels: kind/QA

#1288 ci: fix SeedImage root password
  tests/assets/seedImage-multi.yaml
  tests/assets/seedImage.yaml
Labels: kind/QA

#1292 ci/airgap: delete archive file after extracted it
  tests/e2e/airgap_test.go
Labels: kind/QA

#1294 ci/ui: update check for default cloud config
  tests/cypress/latest/support/commands.ts
Labels: kind/QA

#1261 ci: test booting from raw image
  .github/workflows/cli-k3s-multi_cluster-rm_stable.yaml
  .github/workflows/cli-rke2-multi_cluster-rm_stable.yaml
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_airgap.yaml
  .github/workflows/sub_cli.yaml
  .github/workflows/sub_multi.yaml
  .github/workflows/sub_test_choice.yaml
  .github/workflows/sub_ui.yaml
  .github/workflows/ui-k3s-ibs_stable.yaml
  .github/workflows/ui-k3s-obs_dev.yaml
  .github/workflows/ui-k3s-obs_staging.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-k3s-rm_head_2.7.yaml
  .github/workflows/ui-k3s-rm_head_2.8.yaml
  .github/workflows/ui-k3s-rm_head_2.9.yaml
  .github/workflows/ui-k3s-rm_stable.yaml
  .github/workflows/ui-obs-manual-workflow.yaml
  .github/workflows/ui-rke2-ibs_stable.yaml
  .github/workflows/ui-rke2-obs_dev.yaml
  .github/workflows/ui-rke2-obs_staging.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_stable.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
  .github/workflows/ui-rke2-rm_head_2.7.yaml
  .github/workflows/ui-rke2-rm_head_2.8.yaml
  .github/workflows/ui-rke2-rm_head_2.9.yaml
  .github/workflows/ui-rke2-rm_stable.yaml
  tests/cypress/latest/fixtures/custom_cloud-config.yaml
  tests/cypress/latest/fixtures/custom_cloud-config_with_reset.yaml
  tests/cypress/latest/plugins/index.ts
  tests/cypress/latest/support/commands.ts
  tests/e2e/bootstrap_test.go
  tests/e2e/suite_test.go
  tests/e2e/ui_test.go
  tests/scripts/install-vm
  tests/scripts/start-cypress-tests
Labels: kind/QA

#1299 ci/ui: fix elemental operator upgrade
  .github/workflows/sub_ui.yaml
  tests/cypress/latest/e2e/unit_tests/upgrade-operator.spec.ts
  tests/cypress/latest/plugins/index.ts
  tests/scripts/start-cypress-tests
Labels: kind/QA

#1314 ci: fix OS images name
  .github/workflows/cli-k3s-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/cli-k3s-os-upgrade.yaml
  .github/workflows/cli-rke2-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-k3s-os-upgrade-rm_stable.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.7.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.8.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_head_2.9.yaml
  .github/workflows/ui-rke2-os-upgrade-rm_stable.yaml
  tests/scripts/build-airgap
Labels: kind/QA

#1317 ci/multi: fix the OS image used
  .github/workflows/sub_multi.yaml
  .github/workflows/sub_test_choice.yaml
Labels: kind/QA

#1318 ci/ui: fix chatmuseum script for operator version
  .github/workflows/sub_ui.yaml
  tests/Makefile
  tests/scripts/deploy-chartmuseum
Labels: kind/QA

#1321 Fix RT ISO name
  .obs/dockerfile/micro-rt-iso/Dockerfile
Labels: area/build

#1326 ci/cli: fix PXE boot
  .github/workflows/sub_airgap.yaml
  .github/workflows/sub_cli.yaml
  .github/workflows/sub_multi.yaml
  .github/workflows/sub_ui.yaml
  tests/Makefile
  tests/scripts/get-boot-files-for-pxe
Labels: kind/QA

#1330 ci/cli: add support for snapshotter option
  .github/actions/logs-and-summary/action.yaml
  .github/workflows/cli-rke2-hardened-rm_head_2.7.yaml
  .github/workflows/cli-rke2-hardened-rm_head_2.8.yaml
  .github/workflows/cli-rke2-hardened-rm_head_2.9.yaml
  .github/workflows/cli-rke2-hardened-rm_stable.yaml
  .github/workflows/cli-rke2-hardened-upgrade-reset-rm_stable.yaml
  .github/workflows/cli-rke2-ibs_stable.yaml
  .github/workflows/cli-rke2-multi_cluster-rm_stable.yaml
  .github/workflows/cli-rke2-obs_dev.yaml
  .github/workflows/cli-rke2-obs_staging.yaml
  .github/workflows/cli-rke2-os-upgrade-rm_stable.yaml
  .github/workflows/cli-rke2-os-upgrade.yaml
  .github/workflows/cli-rke2-reset-rm_head_2.7.yaml
  .github/workflows/cli-rke2-reset-rm_head_2.8.yaml
  .github/workflows/cli-rke2-reset-rm_head_2.9.yaml
  .github/workflows/cli-rke2-reset-rm_stable.yaml
  .github/workflows/cli-rke2-rm_head_2.7.yaml
  .github/workflows/cli-rke2-rm_head_2.8.yaml
  .github/workflows/cli-rke2-rm_head_2.9.yaml
  .github/workflows/cli-rke2-rm_stable.yaml
  .github/workflows/cli-rke2-sequential-rm_stable.yaml
  .github/workflows/master_e2e.yaml
  .github/workflows/sub_airgap.yaml
  .github/workflows/sub_cli.yaml
  .github/workflows/sub_multi.yaml
  .github/workflows/sub_test_choice.yaml
  tests/assets/machineRegistration-multi.yaml
  tests/assets/machineRegistration.yaml
  tests/e2e/configure_test.go
  tests/e2e/multi-cluster_test.go
  tests/e2e/suite_test.go
Labels: kind/QA

#1332 ci: update golang dependancies
  tests/go.mod
  tests/go.sum
Labels: kind/QA

#1333 ci: fix lint workflow
  .github/workflows/lint.yaml
  tests/cypress/latest/package.json
Labels: kind/QA
