Repository rancher/elemental, pull requests merged in 2024-01, with the labels that each got.

#1160 Mention elemental-rpmlintrc as Source in spec
  .obs/specfile/elemental.spec
  tests/e2e/app_test.go
  tests/e2e/backup-restore_test.go
  tests/e2e/bootstrap_test.go
  tests/e2e/configure_test.go
  tests/e2e/helpers/elemental/elemental.go
  tests/e2e/helpers/misc/misc.go
  tests/e2e/helpers/network/network.go
  tests/e2e/install_test.go
  tests/e2e/logs_test.go
  tests/e2e/multi-cluster_test.go
  tests/e2e/reset_test.go
  tests/e2e/seedImage_test.go
  tests/e2e/suite_test.go
  tests/e2e/ui_test.go
  tests/e2e/uninstall-operator_test.go
  tests/e2e/upgrade_test.go
Labels: area/build

#1162 Mention elemental-rpmlintrc as Source in spec
  .obs/specfile/elemental.spec
Labels: area/build

#1035 ci: add airgap e2e test (#1034)
  .github/workflows/cli-k3s-airgap_rm_latest_dev.yaml
  .github/workflows/cli-k3s-airgap_rm_stable.yaml
  .github/workflows/master-airgap.yaml
  README.md
  tests/Makefile
  tests/assets/cluster-airgap.yaml
  tests/assets/net-default-airgap.xml
  tests/e2e/airgap_test.go
  tests/e2e/configure_test.go
  tests/e2e/install_test.go
  tests/e2e/seedImage_test.go
  tests/e2e/suite_test.go
  tests/scripts/build-airgap
  tests/scripts/deploy-airgap
Labels: kind/QA, area/airgap

#1180 ci: use the more official qase-ginkgo library
  tests/e2e/helpers/qase/README.md
  tests/e2e/helpers/qase/qase.go
  tests/e2e/helpers/qase/qase_example_test.go
  tests/e2e/helpers/qase/suite_test.go
  tests/e2e/suite_test.go
  tests/go.mod
  tests/go.sum
  tests/qase/qase_cmd.go
Labels: kind/QA

#1181 ci: fix clean-runner job
  .github/workflows/master-e2e.yaml
Labels: kind/QA

#1185 ci: fix delete-runner
  .github/workflows/master-e2e.yaml
Labels: kind/QA

#1182 ci/ui: use auto qase run id mode
  .github/workflows/ui-k3s-ibs_stable.yaml
  .github/workflows/ui-k3s-obs_dev.yaml
  .github/workflows/ui-k3s-obs_staging.yaml
  .github/workflows/ui-k3s-os-upgrade.yaml
  .github/workflows/ui-rke2-ibs_stable.yaml
  .github/workflows/ui-rke2-obs_dev.yaml
  .github/workflows/ui-rke2-obs_staging.yaml
  .github/workflows/ui-rke2-os-upgrade.yaml
Labels: kind/QA
