Repository rancher/elemental, pull requests merged in 2025-04, with the labels that each got.

#1692 ci: fix GCP zones and rebalance scheduling hours
  .github/workflows/README.md
  .github/workflows/SCHEDULING.md
  .github/workflows/cli-full-backup-restore-matrix.yaml
  .github/workflows/cli-k3s-airgap-matrix.yaml
  .github/workflows/cli-k3s-downgrade-matrix.yaml
  .github/workflows/cli-k3s-matrix.yaml
  .github/workflows/cli-k3s-selinux-matrix.yaml
  .github/workflows/cli-k3s-upgrade-matrix.yaml
  .github/workflows/cli-multicluster-matrix.yaml
  .github/workflows/cli-regression-matrix.yaml
  .github/workflows/cli-rke2-matrix.yaml
  .github/workflows/cli-rke2-upgrade-matrix.yaml
  .github/workflows/ui-k3s-upgrade-matrix.yaml
  .github/workflows/ui-rke2-matrix.yaml
  .github/workflows/ui-rke2-upgrade-matrix.yaml
  README.md
Labels: area/CI

#1693 ci/ui: fix test for rancher:head
  tests/cypress/latest/e2e/unit_tests/deploy_app.spec.ts
  tests/cypress/latest/e2e/unit_tests/first_connection.spec.ts
  tests/cypress/latest/support/elemental.ts
Labels: kind/QA

#1695 ci/airgap: fix K3s downstream version
  .github/workflows/cli-k3s-airgap-matrix.yaml
Labels: area/airgap, area/CI

#1697 ci: add missing badge for K3s CLI tests
  README.md
Labels: area/CI

#1698 ci/ui: disable container registry for marketplace
  tests/cypress/latest/support/elemental.ts
Labels: kind/QA

#1701 ci/cli: remove downgrade test
  .github/workflows/README.md
  .github/workflows/cli-k3s-downgrade-matrix.yaml
  .github/workflows/cli-regression-matrix.yaml
  README.md
Labels: area/CI
